### ISSUE TITLE
Fix cleanup section 

### ISSUE THREAD

**Issue by rudpot** [aws-samples/aws-fault-injection-simulator-workshop#155]
As per @teddyaryono review the cleanup section leaves behind resources. Find the source (probably CI/CD stack) and update cleanup procedure.

Deleting `FisStackVpc` is failed due to the dependency violation. There is 1 EC2 instance with following tags that need to be deleted prior to the VPC deletion.
    * Key: `aws:cloudformation:logical-id`, Value: `instance0B661231D`
    * Key: `aws:cloudformation:stack-name`, Value: `fisWorkshopDemo`
    * Key: `FIS-Target`, Value: `true`
    * Key: `aws:cloudformation:stack-id	`, Value: `arn:aws:cloudformation:ap-southeast-1:810259017959:stack/fisWorkshopDemo/0b883280-fde7-11eb-862e-0a51f5211668`
    * Key: `Name`, Value: `FisExampleStack/instance-0`
* @taryono - 2021-08-16 - See previous questions for some resources that is not being cleaned up.

**Comment by mjkubba** [comment]
Fixed by #156

**Comment by rudpot** [comment]
@mjkubba - I thought this was about or included `cleanup.sh` leaving things behind. I don't see that fixed by #156?

**Comment by mjkubba** [comment]
@rudpot I didn't see any leftovers from my previous deploy/cleanup cycle, checked with Benoit de Chateauvieux, he confirmed that PR is the fix for this.
