### ISSUE TITLE
CICD experiment fails with experiment templates without names

### ISSUE THREAD

**Issue by ferngus** [aws-samples/aws-fault-injection-simulator-workshop#157]
When CICD pipeline is triggered, it invokes a build in CodeBuild that runs runExperiment.py. The python script iterates over existing FIS Experiment Templates and expects all of them to have Name tags. If one of them does not have it, the script will fail. 

Solution: properly handle the cases when Experiment Templates don't have Name tags.

**Comment by mjkubba** [comment]
Fixed with #159
