### ISSUE TITLE
Fix cleanup section to include SSM document

### ISSUE THREAD

**Issue by rudpot** [aws-samples/aws-fault-injection-simulator-workshop#162]
Opening on behalf of @haeree - The resources retained - SSM document `TerminateAsgInstancesWithSsm` - update cleanup section to either remove or mention this document.

**Comment by mjkubba** [comment]
Tested the cleanup process, there was no documents left uncleaned,
@haeree what was the steps you took to produce this?

**Comment by haeree** [comment]
@mjkubba Seems it was fixed at some point. 
There was a SSM document left when the workshop was initially released.
