### ISSUE TITLE
/aws/lambda/FisStackEks-awscdkawseks* log groups should have Retention set to 90 days 

### ISSUE THREAD

**Issue by FireballDWF** [aws-samples/aws-fault-injection-simulator-workshop#217]
/aws/lambda/FisStackEks-awscdkawseks* and /aws/lambda/FisStackLoadGen-LoadGenerator* log groups should have Retention set to 90 days, just like how the /aws/lambda/fis-workshop-api-* ones have it set

**Comment by rudpot** [comment]
I know how to do this for the lambda. Still looking how to do this for the eks.Cluster construct. If anyone knows I am all ears.
