### ISSUE TITLE
ssm start-session command does not work on MacOSX

### ISSUE THREAD

**Issue by zxkane** [aws-samples/aws-fault-injection-simulator-workshop#246]
Following [the guide](https://github.com/aws-samples/aws-fault-injection-simulator-workshop/blob/main/workshop/content/030_basic_content/040_ssm/040_windows_stress/_index.md#use-aws-systems-manager-session-manager-to-connect-to-target-instance) to forward Windows remote desktop to local port, see below error on MacOSX/zsh,

```bash
❯ # This presumes you set TMP_INSTANCE (see above)
aws ssm start-session --target ${TMP_INSTANCE} --document-name AWS-StartPortForwardingSession --parameters "portNumber"=["3389"],"localPortNumber"=["56788"]
zsh: no matches found: portNumber=[3389],localPortNumber=[56788]
```

Changed to below command it works,

```bash
aws ssm start-session --target ${TMP_INSTANCE} --document-name AWS-StartPortForwardingSession --parameters portNumber=3389,localPortNumber=56788

Starting session with SessionId: xxx
Port 56788 opened for sessionId xxx.
Waiting for connections...
```

**Comment by rudpot** [comment]
@mjkubba / @virtlima - this looks like #242 didn't solve the problem. The suggested solution in this issue looks more reasonable to me than the fix that we put in but I don't have the time right now to fix it, could one of you confirm? Can you make sure to try with both zsh and bash? My suspicion is that (1) the exposed square brackets are a problem and (2) that in the shorthand notation the square brackets shouldn't be needed at all.
