### ISSUE TITLE
Failed to initialize node setting for Cloud 9 environment 

### ISSUE THREAD

**Issue by naxxster** [aws-samples/aws-fault-injection-simulator-workshop#312]
When I initialize the Cloud 9 environment according to the workshop, latest stable node version installed by nvm is `v18.1.0`.

```bash
Admin:~/environment $ nvm install stable 
Downloading and installing node v18.1.0...
```

After the installation of node, subsequence execution of node failed to run with following errors.
```
Admin:~/environment $ npm install -g typescript
node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
```

* Cloud 9 instance AMI name : Cloud9AmazonLinux2-2022-04-28T13-41

**Comment by rudpot** [comment]
Confirmed as an issue. Workaround is to use 
```
nvm install --lts
nvm use --lts
```
