### ISSUE TITLE
Cloud9 Provisioning Problems

### ISSUE THREAD

**Issue by JensRichnow** [aws-samples/aws-fault-injection-simulator-workshop#408]
Hi, I started the workshop today but couldn't go passed AWS resource provisioning step which failed. I was trying to fix manually as issues popped up but gave up in the end.

* Installing node via `nvm install --lts` as in the script provided gives right now v18.14.2
* This fails the following installations, for instance of aws-cdk as GLIBC_2.27 or GLIBC_2.28 are not supported. This goes back to the platform selection for the Cloud9 environment: there are two options, and neither support the GLIBC versions ...
* In either case I tried node with lower versions, first v16.3.0 as this is still supported during the next step, and later to v16.10.0 as this seems to be the version supported by the EKS provisioning ...
* now it turns out that the EKS version 1.20 is not supported anymore on AWS (the lowest being 1.22 as per website)
* trying to manually fix the `aws-cdk-lib` to a later version did open up more problems ...

Does somebody else experienced this and if so, what is the best way to get the workshop going? 

Many Thanks

P.S.: The workshop link: https://catalog.us-east-1.prod.workshops.aws/workshops/5fc0039f-9f15-47f8-aff0-09dc7b1779ee/en-US

**Comment by rudpot** [comment]
Thanks for the bug report - looking into this. Definitely need to update EKS and will look into the cdk issues as well.
