### ISSUE TITLE
Add Name tags to experiments run by CI/CD pipeline

### ISSUE THREAD

**Issue by rudpot** [aws-samples/aws-fault-injection-simulator-workshop#45]
Currently experiments run by the CI/CD pipeline have no name in the list. Add a `Name` tag. I would suggest using a descriptive part like `cicd-` followed by a stage name `stopinstances-` followed by the git hash that triggered the experiment.

**Comment by mjkubba** [comment]
Experiments do have tags, a quick git blame shows ferngus added the tags to the py file
